apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  template:
    spec:
      containers:
      - name: python-api
        image: docker.io/iradics1974/python-api:33fff19
