apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Enables automatic discovery of repo credentials
  application.instanceLabelKey: argocd.argoproj.io/instance
  repository.credentials: |
    - url: https://github.com/
