apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/iradics1974/gitops-lab.git'
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true   # <── THIS IS THE KEY
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
