apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-api-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iradics1974/gitops-lab
    targetRevision: main
    path: apps/python-api/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
