apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-api
  namespace: argocd
  annotations:
    # Image updater configuration
    argocd-image-updater.argoproj.io/image-list: python-api=docker.io/iradics1974/python-api
    argocd-image-updater.argoproj.io/python-api.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default

  source:
    repoURL: https://github.com/iradics1974/gitops-lab
    targetRevision: main
    path: apps/python-api/manifests
    kustomize: {}    # Activate Kustomize for this folder

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
